version: "3.5"

services:
  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      BASE_URL: ${BASE_URL}
      VF_USERNAME: ${VF_USERNAME}
      VF_PASSWORD: ${VF_PASSWORD}
      VF_APPKEY: ${VF_APPKEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      UNIFI_IP: ${UNIFI_IP}
      UNIFI_API_TOKEN: ${UNIFI_API_TOKEN}
      EXPORT_USERS: ${EXPORT_USERS}
      EXPORT_FLIGHTS: ${EXPORT_FLIGHTS}
      EXPORT_RESERVATIONS: ${EXPORT_RESERVATIONS}
    volumes:
      - ./config:/app/config
    command: ["./entrypoint.sh"]

volumes:
  db-data:
